### ISSUE TITLE
Update examples to use v2 components

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#259]
# Why
In addition to our playground applications we have 4 example applications that we host on Vercel. We use them for two things:
- validate that our published packages work
- demonstrate the packages to external developers

These are the examples:
- https://react.demo.corbado.io/
- https://web-js-script.demo.corbado.io/
- https://web-js.demo.corbado.io/
- https://next.demo.corbado.io/

Right now these examples still use the v1 components. In this issue we want to update all of them to use version 2.
For this the latest v2 version should be used (2.0.3-alpha.0).
In addition we want to fix typos in the examples. Currently known:
- The @corbado/react package provides (web-js examples)
- @Adam3371 please go through the examples to check if there are other typos

# Acceptance criteria
- [ ] all 4 examples work and use the new components
- [ ] the typos in web-js examples ("The @corbado/react package provides") are fixed

**Comment by Adam3371** [comment]
https://next.demo.corbado.io/ 
- [x] "Go to Application" button gives a server side error
- [x] Passkey list component + Create a passkey button is not constrained to a fixed width and is super wide.
- [x] When signing out, a picture of 3 login steps is shown instead of the component

https://react.demo.corbado.io/
- [x] "The <CorbadoAuth /> component allows your users to signUp and login with their passkeys" change signUp to sign up

https://web-js.demo.corbado.io/
- [x] First line: the @corbado/react -> @corbado/web-js
- [x] signUp to sign up (Like in react)
- [x] Second "Change Dark Mode" headline change to "Use Custom Translations" 
- [x] Logout not possible

https://web-js-script.demo.corbado.io/
- [x] First line: the @corbado/react -> @corbado/web-js
- [x] signUp to sign up (Like in react)
- [x] Second "Change Dark Mode" headline change to "Use Custom Translations" 
- [x] Component disappears at every action

**Comment by Aby-JS** [comment]
@Adam3371 all the fixes except for point 1 and 3 for nextjs demo are done. For NextJS demo I am waiting on some BE fixes after that this demo will be fixed

**Comment by Adam3371** [comment]
Feedback:

- [x] After **Logout** show the **Login** screen. (For Next, React, Web-js, web-js script)
- [x] Customized Theme + Dark mode: Make link color (sign up, log in ecc.) lighter for better contrast. (React, Web-js, script)

https://next.demo.corbado.io/
- [x] Sign out not working. (when clicking on sign out and then "Go to Application", im logged in again. The cookie is not short_session cookie is not removed)
- [x] In ca. 50% of the times at signup, after the passkey appended screen, user gets redirected to another signup instead of the dashboard. 

https://web-js.demo.corbado.io/
- [x] When changing mode, theme or translations, user data gets lost (in react it doesn't)
- [x] Emerald Funk + Dark mode off: In passkey list "apple" icon is black and should be white (Icon different from react)


https://web-js-script.demo.corbado.io/
- [x] "!" icon in textfield-error messages are always black (should be red)
- [x] When changing mode, theme or translations, user data gets lost (in react it doesn't)
- [x] Check all points from web-js as I cannot test them now
